name: First workflow

on:
  push:
    # branches:
    #   - main
 
jobs:
  python_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run python code
        run: python index.py
        

      - name: Run one-line script
        run: echo,"Hello World"
